todolist/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^login/$', 'todolist.login.login_view'),
    url(r'^accounts/logout/$', 'todolist.login.Logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'todo.views.dashboard', name="dashboard"),
    url(r'^todo/(?P<stat>done|list)/$', 'todo.views.MyToDo', name="mytodo"),
    url(r'^cron/(?P<stat>done|list)/$', 'todo.views.CronToDo', name="mycron"),
    #add task and project
    url(r'^todo/add/$', 'todo.views.AddBusiness', name="addbusinesstask"),
    url(r'^base/add/$', 'todo.views.AddBaseItem', name="addbaseitem"),
    url(r'^todo/(?P<pid>\d+)$', 'todo.views.TaskView', name="taskview"),
    # add project
    url(r'^project/add/$', 'todo.views.AddProject', name="addproject"),
    url(r'^project/edit/(?P<id>\d+)/$', 'todo.views.EditProjectList', name="editproject"),
    url(r'^project/(?P<stat>done|list)/$', 'todo.views.ViewProjectList', name="projectlist"),
    url(r'^project/(?P<pid>\d+)/$', 'todo.views.ViewSubProject', name="subprojectlist"),
    #url(r'^project/(?P<pid>\d+)/add/$', 'todo.views.AddSubProject', name="addsubproject"),
    url(r'^task/edit/(?P<id>\d+)/$', 'todo.views.EditTask', name="edittaskitem"),
    #
    url(r'^base/(?P<stat>list|done)/$', 'todo.views.BaseItemList', name='baseitemlist'),
    url(r'^delitem/$', 'todo.views.DelItem', name='delitem'),
    url(r'^trash/$', 'todo.views.Trashlist', name='trashlist'),
    url(r'^mygroup/$', 'todo.views.MyGroup', name='mygroup'),
    url(r'^search/$', 'todo.views.Search', name='searchlist'),
    url(r'^todo/multi/clock/$', 'todo.views.MultiAdd', name='multiaddtask'),
    url(r'^todo/multi/count/$', 'todo.views.MultiAddCount', name='multiaddtaskcount'),
    #gant
    url(r'^ganttapi/$', 'todo.gantt.get_list_gantt'),
    url(r'^gantt/(?P<gid>\d+)/$', 'todo.views.showgantt', name='gantt'),
    #statistics
    url(r'^statistics/$', 'todo.views.TaskStatistics', name='taskstatistics'),

]

#handler403 = 'todo.views.page_forbidden'
#handler404 = 'todo.views.page_not_found'
#handler500 = 'todo.views.page_error'

todo/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User, Group
from todo.sendmail import Notification
from todo.senddata import SendTodoData
from decimal import Decimal
import datetime


class ParentType(models.Model):


    name = models.CharField(u'名称', max_length=100)

    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = u'父级分类'
        verbose_name_plural = verbose_name


class Type(models.Model):

    TYPE_CHOICES = (
        ('time', u'耗时'),
        ('count', u'计次'),
    )

    name = models.CharField(u'名称', max_length=40)
    base = models.DecimalField(u'KPI基本分',
                                max_digits=5,
                                 decimal_places=2,
                                 default=1.00,
                                 blank=True,
                                 null=True)

    value = models.DecimalField(u'难度系数',
                                max_digits=5,
                                 decimal_places=3,
                                 default=1.00,
                                 blank=True,
                                 null=True)
    type = models.CharField(u'类型', max_length=5, choices=TYPE_CHOICES, default='count')
    parent = models.ForeignKey(ParentType, verbose_name=u'父级', default=1)

    def getvalue(self):

        return self.base * self.value

    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = u'绩效分类'
        verbose_name_plural = verbose_name

class Holidays(models.Model):

    date = models.DateField(u'日期')
class CronTask(models.Model):

    PRIORITY_CHOICES = (
        (1, u'紧急'),
        (2, u'重要'),
        (3, u'高'),
        (4, u'正常'),
        (5, u'低'),
    )

    PERIOD_CHOICES = (
        ('day', u'每日'),
        ('weekday', u'每周'),
        ('month', u'每月'),
        ('quarter', u'每季'),
    )
    title = models.CharField(u'任务名', max_length=140)
    type = models.ForeignKey(Type, verbose_name=u'业务类型', blank=True, null=True)
    period = models.CharField(u'任务周期', choices=PERIOD_CHOICES, default='day', max_length=10)
    created_by = models.ForeignKey(User, related_name='cron_created_by', verbose_name=u'创建人', blank=True, null=True)
    assigned_to = models.ManyToManyField(User, verbose_name=u'分配给')
    note = models.TextField(u'备注', blank=True)
    priority = models.IntegerField(
        (u'权重'),
        choices=PRIORITY_CHOICES,
        default=4,
        blank=3,
        help_text=(u'1 = 最高权重, 5 = 最低权重'),
        )
    is_active = models.BooleanField(u'有效', default=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'计划任务'
        verbose_name_plural = verbose_name


class ProjectList(models.Model):

    STATUS_CHOICES = (
        (1, u'进行中'),
        (2, u'已完成'),
        (3, u'已关闭'),
    )

    name = models.CharField(u'事项名', max_length=60)
    created_date = models.DateField(u'创建日期', auto_now=True)
    created_by = models.ForeignKey(User, related_name='list_created_by', verbose_name=u'创建者')
    assigned_to = models.ManyToManyField(User, related_name='list_assigned_to', verbose_name=u'分配给')
    stat = models.IntegerField(
        (u'状态'),
        choices=STATUS_CHOICES,
        default=1,
        )

    def getsubnum(self):
        try:
            return self.item_set.filter(is_delete=False).count()
        except:
            return 0


    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = u'项目列表'
        verbose_name_plural = verbose_name


class Item(models.Model):

    STATUS_CHOICES = (
        (1, u'未开始'),
        (2, u'进行中'),
        (3, u'已完成'),
        (4, u'已关闭'),
    )

    PRIORITY_CHOICES = (
        (1, u'紧急'),
        (2, u'重要'),
        (3, u'高'),
        (4, u'正常'),
        (5, u'低'),
    )


    TASK_TYPE = (
        (1, u'基本任务'),
        (2, u'待办任务'),
        (3, u'项目任务'),
        (4, u'定期任务'),
    )
    title = models.CharField(u'任务名', max_length=140)
    project = models.ForeignKey(ProjectList, verbose_name=u'项目名称', blank=True, null=True)
    type = models.ForeignKey(Type, verbose_name=u'业务类型', blank=True, null=True)
    tasktype = models.IntegerField(
        (u'任务类型'),
        choices=TASK_TYPE,
        default=1,
    )

    created_date = models.DateTimeField(u'创建时间', blank=True, null=True, auto_now_add=True)
    #start_time = models.DateTimeField(u'任务开始时间', blank=True, null=True)
    updte_time = models.DateTimeField(u'更新时间', auto_now=True)
    due_date = models.DateField(u'截止日期', blank=True, null=True)
    progress = models.CharField(u'进度', blank=True, max_length=3, default='0', help_text=u'输入100内数值')
    length = models.DecimalField(u'持续时间',
                                max_digits=5,
                                decimal_places=3,
                                default=1,
                                blank=True,
                                null=True,
                                help_text=u'小时 此为默认值，非说明不要修改')
    count = models.IntegerField(u'次数', blank=True, null=True, default=1)
    status = models.IntegerField(
        (u'任务状态'),
        choices=STATUS_CHOICES,
        default=1,
    )
    #extra_stat -1： 未分配 0：正常  1：垃圾箱
    is_delete = models.BooleanField(default=False)
    completed_date = models.DateTimeField(u'完成日期', blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='item_created_by', verbose_name=u'创建人')
    assigned_to = models.ForeignKey(User, related_name='item_assigned_to',
                                    verbose_name=u'分配给', blank=True, null=True)
    note = models.TextField(u'备注', blank=True)
    priority = models.IntegerField(
        (u'权重'),
        choices=PRIORITY_CHOICES,
        default=4,
        blank=3,
        help_text=(u'1 = 最高权重, 5 = 最低权重'),
        )

    #锁定后无法修改截至日期，无法删除
    lock = models.BooleanField(default=False) #False 正常 True 锁定


    def _get_status(self):
        """
        Displays the ticket status
        """
        return u'%s' % (self.get_status_display())
    get_status = property(_get_status)

    def _get_priority(self):
        return u'%s' % (self.get_priority_display())
    get_priority = property(_get_priority)

    def overdue_status(self):
        """
        返回是否逾期
        :return:
        """
        if self.due_date and self.status in [1,2] and datetime.date.today() > self.due_date:
            return True

    def com_due_status(self):

        if self.due_date and self.completed_date > self.due_date:
            return True

    def per_value(self):
        try:
            if self.tasktype == 3:
                perfvalue = self.length

            else:
                perfvalue = Decimal(str(self.type.base)) * Decimal(str(self.type.value)) * \
                            Decimal(str(self.length)) * Decimal(str(self.count))


            return perfvalue
        except:
            return 0

    def __unicode__(self):
        return '%s' % self.title

    # Auto-set the item creation / completed date
    def save(self):

        """
        如果状态为3（完成）且未锁定， 修改为锁定
        """

        if self.created_by and not self.assigned_to:
            self.assigned_to = self.created_by

        if self.status == 3 and not self.lock:
            self.completed_date = datetime.datetime.now()
            self.lock = True
            self.progress = '100'

            try:
                if self.tasktype == 3:
                    perfvalue = self.length
                    type = 'pro'
                else:
                    perfvalue = Decimal(str(self.type.base)) * Decimal(str(self.type.value)) * \
                                Decimal(str(self.length)) * Decimal(str(self.count))
                    type = 'base'

                try:
                    owner = self.assigned_to.username
                except:
                    owner = self.created_by.username
              
                result = SendTodoData(title=self.title, value=perfvalue, owner=owner, type=type)
                if not result:
                    raise Exception('Error')
            except Exception, e:
                raise Exception('Error from source %s' % e)

        if self.status == 1 and self.tasktype != 1:
            a = Notification(u'您有新的任务需要处理')

            msg = u'任务: %s <br><br>' \
                  u'创建人: %s<br><br>' \
                  u'<a href="http://todo.example.com/">详细信息请访问任务管理系统</a><br>' % \
                  (self.title, self.created_by.username)
            try:
                sender = self.assigned_to.username
            except:
                sender = self.task.created_by.username

            a.send_email(sender, msg)


        super(Item, self).save()


    class Meta:
        ordering = ["priority"]
        verbose_name = u'任务'
        verbose_name_plural = verbose_name


class ItemComment(models.Model):
    """
    Not using Django's built-in comments because we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """
    author = models.ForeignKey(User)
    task = models.ForeignKey(Item)
    date = models.DateTimeField(default=datetime.datetime.now)
    body = models.TextField(blank=True)
    reply = models.ForeignKey('self', verbose_name=u'上级评论', blank=True, null=True, related_name='parent_comment')

    def __unicode__(self):
        return '%s - %s' % (
            self.author,
            self.date,
        )
    class Meta:
        verbose_name = u'评论'
        verbose_name_plural = verbose_name

    def save(self):

        a = Notification(u'您有新的评论')

        msg = u'任务: %s <br><br>' \
              u'评论人: %s<br><br>' \
              u'内容: %s <br><br>' \
              u'<a href="http://todo.example.com/">详细信息请访问任务管理系统</a><br>' % \
              (self.task.title, self.author.username, self.body)
        try:
            sender = self.task.assigned_to.username
        except:

templates/todo/mygroup.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}任务列表{% endblock %}

{% block staticcss %}

    <!-- DataTables CSS -->
    <link href="{% static "vendor/datatables-plugins/dataTables.bootstrap.css" %}" rel="stylesheet">

    <link href="{% static "dist/css/jquery.datetimepicker.css" %}" rel="stylesheet">

    <style>
        .datetimepicker {z-index:9999 !important;}

    </style>

{% endblock %}

{% block staticjs %}





    <script src="{% static "vendor/datatables/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables-plugins/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "js/bootstrap-datetimepicker.js" %}"></script>
    <script type="text/javascript">

    $(".js-example-basic-multiple").select2();

    $(".form_datetime").datetimepicker({
        format: "yyyy-mm-dd",
        minView: 2,
        autoclose: true,
        todayBtn: true,
        pickerPosition: "bottom-left",
        language: 'zh',
        todayHighlight: true
    });

     $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true,
                "language": {

                        "sProcessing":   "处理中...",
                        "sLengthMenu":   "显示 _MENU_ 项结果",
                        "sZeroRecords":  "没有匹配结果",
                        "sInfo":         "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                        "sInfoEmpty":    "显示第 0 至 0 项结果，共 0 项",
                        "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
                        "sInfoPostFix":  "",
                        "sSearch":       "搜索:",
                        "sUrl":          "",
                        "sEmptyTable":     "表中数据为空",
                        "sLoadingRecords": "载入中...",
                        "sInfoThousands":  ",",
                        "oPaginate": {
                            "sFirst":    "首页",
                            "sPrevious": "上页",
                            "sNext":     "下页",
                            "sLast":     "末页"
                        },
                        "oAria": {
                            "sSortAscending":  ": 以升序排列此列",
                            "sSortDescending": ": 以降序排列此列"
                        }
                }
        });
    });

    </script>


{% endblock %}

{% block content %}


<!-- Page Content -->
    <div id="page-wrapper">


        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}><strong>{{ message }}</strong></div>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="container-fluid">
            <div class="row">


                    <ol class="breadcrumb">
                        <li><a href="/"><span class="glyphicon glyphicon-home"></span></a></li>
                        <li class="active">待办任务列表</li>
                        <li class="active"><a href="javascript:history.go(-1);">返回前页</a></li>
                    </ol>

            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        <!-- /.row -->


        {% if search_results %}
        <div class="row">
            <div class="col-lg-12">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        本周任务列表

                        <div class="pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-chevron-down"></i>

                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li>
                                        <button  class="btn btn-outline" data-toggle="modal" data-target="#myExport">
                                        导出 <i class="glyphicon glyphicon-export"></i>
                                        </button>

                                    </li>



                                </ul>
                            </div>
                        </div>

                    </div>
                    <!-- /.panel-heading -->

                    <div class="panel-body">

                        <!--表单报错显示-->
                        {% if form.errors %}

                            {% for field, error in form.errors.items %}
                                <div class="alert alert-error">
                                    {{ field }} <code>{{ error }}</code>
                                </div>
                            {% endfor %}


                        {% endif %}
                        <div class="dataTable_wrapper">
                        <form role="form" method="post" action=".">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>选择</th>
                                        <th>ID</th>
                                        <th>任务名称</th>
                                        <th>任务类型</th>
                                        <th>业务类型</th>
                                        <th>权重</th>
                                        <th>创建人</th>
                                        <th>创建日期</th>
                                        <th>截止日期</th>
                                        <th>分配给</th>
                                        <th>状态</th>
                                        <th>评论</th>
                                        <th>绩效值</th>
                                        <th>操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for list in search_results %}
                                    <tr class="odd gradeX">
                                        <td><input type="checkbox" value="{{ list.id }}" name="mark_done"></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td><p title="{{ list.title }}">{{ list.title|slice:'20' }}</p></td>
                                        <td>{{ list.get_tasktype_display }}</td>
                                        <td><p title="{{ list.type.name }}"> {{ list.type.name |slice:'10'}}</p></td>
                                        <td class="{% ifequal list.priority 1 %}danger {% endifequal %}">{{ list.get_priority_display }}</td>
                                        <td>{{ list.created_by }}</td>
                                        <td>{{ list.created_date }}</td>
                                        <td class="center">{{ list.due_date|default:'' }}</td>
                                        <td class="center">{{ list.assigned_to|default:'' }}</td>
                                        <td>{{ list.get_status_display }}</td>
                                        <td><a href="#">{{ list.itemcomment_set.all.count }}</a> </td>
                                        <td>{{ list.per_value }}</td>
                                        <td>
                                        <a class="btn btn-outline btn-primary" href="{% url 'taskview' list.id %}">查看</a>

                                        <a class="btn btn-outline btn-info" href="{% url 'edittaskitem'  list.id %}">编辑</a>

                                        <a class="btn btn-outline btn-danger" href="#" data-href="{% url 'delitem'%}?type=task&id={{ list.id }}"
                                           data-toggle="modal" data-target="#confirm-delete">删除</a>

                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                            <button type="submit" class="btn btn-outline btn-danger" name="mark" >批量删除</button>
                        </form>
                        </div>
                    </div>
                    <!--end panel-body-->
                </div>

            </div>
        </div>

        {% endif %}
    </div>
    <form role="form" method="post">
    <div class="modal fade" id="myExport" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">

            <div class="modal-body">
            确认导出记录吗？
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            <button class="btn btn-primary" type="submit" name="export">导出</button>
            </div>
            </div>
            </div>
        </div>
    </form>
    <!--表单报错显示-->
        {% if form.errors %}

            {% for field, error in form.errors.items %}
                <div class="alert alert-error">
                    {{ field }} <code>{{ error }}</code>
                </div>
            {% endfor %}


        {% endif %}



{% endblock %}

templates/todo/projectlist.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}项目列表{% endblock %}

{% block staticcss %}
    <!-- DataTables CSS -->
<link href="{% static "vendor/datatables-plugins/dataTables.bootstrap.css" %}" rel="stylesheet">


{% endblock %}

{% block staticjs %}

    <script src="{% static "vendor/datatables/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables-plugins/dataTables.bootstrap.min.js" %}"></script>

{% endblock %}

{% block content %}


<!-- Page Content -->
    <div id="page-wrapper">


        <div class="container-fluid">
            <div class="row">


                    <ol class="breadcrumb">
                        <li><a href="/"><span class="glyphicon glyphicon-home"></span></a></li>
                        <li class="active">项目列表</li>
                        <li class="active"><a href="javascript:history.go(-1);">返回前页</a></li>
                    </ol>

            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}><strong>{{ message }}</strong></div>
                {% endfor %}
            </ul>
        {% endif %}

        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        项目列表
                        <div class="pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-chevron-down"></i>

                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li>


                                        <a href="{% url 'addproject' %}">
                                        添加任务
                                        </a>
                                    </li>


                                </ul>
                            </div>
                        </div>


                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>选择</th>
                                        <th>ID</th>
                                        <th>项目名称</th>
                                        <th>创建日期</th>
                                        <th>创建人</th>
                                        <th>项目参与人</th>
                                        <th>子项目</th>
                                        <th>状态</th>
                                        <th>操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for list in project %}
                                    <tr class="odd gradeX">
                                        <td><input type="checkbox" value=""></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ list.name }}</td>
                                        <td>{{ list.created_date }}</td>
                                        <td class="center">{{ list.created_by }}</td>
                                        <td class="center">{% for u in list.assigned_to.all %}{{ u.username }} {% endfor %}</td>
                                        <td>{{ list.getsubnum }}</td>
                                        <td>{{ list.get_stat_display }}</td>
                                        <td>
                                        <a class="btn btn-outline btn-primary" href="{% url 'gantt' list.id %}">甘特图</a>

                                        <a class="btn btn-outline btn-primary" href="{% url 'subprojectlist' list.id %}">查看</a>

                                        <a class="btn btn-outline btn-danger" href="{% url 'editproject' list.id %}">编辑</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!--end panel-body-->
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/todo/taskdonelist.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}任务列表{% endblock %}

{% block staticcss %}
    <!-- DataTables CSS -->
<link href="{% static "vendor/datatables-plugins/dataTables.bootstrap.css" %}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{% static "vendor/datatables-responsive/dataTables.responsive.css" %}" rel="stylesheet">
{% endblock %}

{% block staticjs %}

    <script src="{% static "vendor/datatables/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables-plugins/ataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "vendor/datatables-responsive/dataTables.responsive.js" %}"></script>
{% endblock %}

{% block content %}


<!-- Page Content -->
    <div id="page-wrapper">


        <div class="container-fluid">
            <div class="row">


                    <ol class="breadcrumb">
                        <li><a href="/"><span class="glyphicon glyphicon-home"></span></a></li>
                        <li class="active">任务列表</li>
                    </ol>

            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
        <!-- /.row -->

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}><strong>{{ message }}</strong></div>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        任务列表

                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">

                        <!--表单报错显示-->
                        {% if form.errors %}

                            {% for field, error in form.errors.items %}
                                <div class="alert alert-error">
                                    {{ field }} <code>{{ error }}</code>
                                </div>
                            {% endfor %}


                        {% endif %}
                        <div class="dataTable_wrapper">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>任务名称</th>
                                        <th>创建人</th>
                                        <th>创建日期</th>
                                        <th>截止日期</th>
                                        <th>分配给</th>
                                        <th>状态</th>
                                        <th>评论</th>
                                        <th>操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for list in tasklist %}
                                    <tr class="odd gradeX">
                                        <td>{{ list.id }}</td>
                                        <td>{{ list.title }}</td>
                                        <td>{{ list.created_by }}</td>
                                        <td>{{ list.created_date }}</td>
                                        <td class="center">{{ list.due_date }}</td>
                                        <td class="center">{{ list.assigned_to }}</td>
                                        <td>{{ list.get_status_display }}</td>
                                        <td><a href="#">{{ list.itemcomment_set.all.count }}</a> </td>
                                        <td>
                                        <a class="btn btn-outline btn-primary" href="{% url 'taskview' list.id %}">查看</a>

                                        <a class="btn btn-outline btn-danger" href="#">编辑</a>

                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!--end panel-body-->
                </div>
            </div>
        </div>
    </div>


{% endblock %}